name: Doridos Backend CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 chekcout
        uses: actions/checkout@v3

      - name: JDK 11 설정
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Gradlew 권한 설정
        run: chmod +x ./gradlew

      - name: Jar 파일 빌드
        run: ./gradlew bootJar

      - name: Docker Hub 로그인
        run: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: alswns7984/doridos

      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: alswns7984/doridos:latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: self-hosted
    if: ${{ needs.docker-build.result == 'success' }}
    needs: [docker-build]
    steps:
      - name: vltur 인스턴스 접속
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VULTR_HOST }}
          username: ${{ secrets.VULTR_USERNAME }}
          password: ${{ secrets.VULTR_PASSWORD }}
          port: ${{ secrets.VULTR_PORT }}
          script: |
            docker stop $(docker ps -a -q)
            docker pull alswns7984/doridos:latest
            docker run -d -p 8080:8080 --name backend alswns7984/doridos:latest
            docker image prune -a -f
